import { IComment, IPost, IUser } from '../types';

export const mockUsers: IUser[] = [
    {
        id: '1',
        username: 'John',
        password: '123',
        email: 'test1@admin.com',
        avatarUrl:
            'https://mykaleidoscope.ru/x/uploads/posts/2022-09/1663110850_6-mykaleidoscope-ru-p-spokoinii-chelovek-vkontakte-8.jpg',
        isOnline: false,
        friends: [],
        inFriendRequest: [],
        outFriendRequest: [],
        unreadMessages: [],
    },
    {
        id: '2',
        password: '123',
        username: 'Pete',
        email: 'test2@admin.com',
        avatarUrl: 'https://api.dicebear.com/7.x/adventurer-neutral/svg',
        isOnline: true,
        friends: [],
        inFriendRequest: [],
        outFriendRequest: [],
        unreadMessages: [],
    },
    {
        id: '3',
        password: '123',
        username: 'Ann',
        email: 'test3@admin.com',
        avatarUrl: 'https://api.dicebear.com/7.x/micah/svg',
        isOnline: false,
        friends: [
            'Tue Mar 19 2024 15:26:56 GMT+0300 (Москва, стандартное время)',
        ],
        inFriendRequest: [],
        outFriendRequest: [],
        unreadMessages: [],
    },
    {
        id: '4',
        password: 'password',
        username: 'Tom',
        email: 'james@gmail.com',
        avatarUrl: 'https://api.dicebear.com/7.x/micah/svg?seed=Felix',
        isOnline: true,
        friends: [],
        inFriendRequest: [],
        outFriendRequest: [],
        unreadMessages: [],
    },
    {
        id: 'Tue Mar 19 2024 14:41:24 GMT+0300 (Москва, стандартное время)',
        username: 'Петя',
        email: 'test@admin.com',
        password: '123',
        isOnline: true,
        friends: [],
        posts: [],
        inFriendRequest: [],
        outFriendRequest: [],
        unreadMessages: [],
    },
    {
        id: 'Tue Mar 19 2024 14:42:45 GMT+0300 (Москва, стандартное время)',
        username: 'Петя',
        email: 'test@admin.com',
        password: '123',
        isOnline: true,
        friends: [],
        posts: [],
        inFriendRequest: [],
        outFriendRequest: [],
        unreadMessages: [],
    },
    {
        id: 'Tue Mar 19 2024 14:47:23 GMT+0300 (Москва, стандартное время)',
        username: 'Игорь',
        email: 'test@admin.com',
        password: '12345',
        isOnline: true,
        friends: [
            'Tue Mar 19 2024 15:26:56 GMT+0300 (Москва, стандартное время)',
        ],
        posts: [],
        inFriendRequest: [],
        outFriendRequest: [],
        unreadMessages: [],
    },
    {
        id: 'Tue Mar 19 2024 15:26:56 GMT+0300 (Москва, стандартное время)',
        username: 'Джон',
        email: 'admin@test.ru',
        password: '123',
        isOnline: true,
        friends: [
            '3',
            'Tue Mar 19 2024 14:47:23 GMT+0300 (Москва, стандартное время)',
        ],
        posts: [],
        inFriendRequest: [],
        outFriendRequest: [],
        unreadMessages: [],
    },
    {
        id: 'Tue Mar 19 2024 20:07:39 GMT+0300 (Москва, стандартное время)',
        username: 'Петя',
        email: 'test@admin.com',
        password: '123',
        isOnline: true,
        friends: [],
        posts: [],
        inFriendRequest: [],
        outFriendRequest: [],
        unreadMessages: [],
    },
    {
        id: 'Tue Mar 19 2024 20:13:00 GMT+0300 (Москва, стандартное время)',
        username: 'Peter',
        email: 'test@admin.com',
        password: '111',
        isOnline: true,
        friends: [],
        posts: [],
        inFriendRequest: [],
        outFriendRequest: [],
        unreadMessages: [],
    },
    {
        id: 'Tue Mar 19 2024 20:18:59 GMT+0300 (Москва, стандартное время)',
        username: 'Peter',
        email: 'test@admin.com',
        password: '123',
        isOnline: true,
        friends: [],
        posts: [],
        inFriendRequest: [],
        outFriendRequest: [],
        unreadMessages: [],
    },
    {
        id: 'Tue Mar 19 2024 20:24:40 GMT+0300 (Москва, стандартное время)',
        username: 'John',
        email: 'test@admin.com',
        password: '111',
        isOnline: true,
        friends: [],
        posts: [],
        inFriendRequest: [],
        outFriendRequest: [],
        unreadMessages: [],
    },
    {
        id: 'Tue Mar 19 2024 21:04:38 GMT+0300 (Москва, стандартное время)',
        username: 'Ваня новый',
        email: 'test@admin.com',
        password: '111',
        isOnline: true,
        friends: [],
        posts: [],
        inFriendRequest: [],
        outFriendRequest: [],
        unreadMessages: [],
    },
    {
        id: 'Tue Mar 19 2024 21:17:09 GMT+0300 (Москва, стандартное время)',
        username: 'rocky',
        email: 'test@admin.com',
        password: '111',
        isOnline: true,
        friends: [],
        posts: [],
        inFriendRequest: [],
        outFriendRequest: [],
        unreadMessages: [],
    },
    {
        id: 'Tue Mar 19 2024 21:18:47 GMT+0300 (Москва, стандартное время)',
        username: 'Ваня',
        email: 'test@admin.com',
        password: '111',
        isOnline: true,
        friends: [],
        posts: [],
        inFriendRequest: [],
        outFriendRequest: [],
        unreadMessages: [],
    },
    {
        id: 'Tue Mar 19 2024 21:19:54 GMT+0300 (Москва, стандартное время)',
        username: 'Ира Петрова',
        email: 'test@admin.com',
        password: '12345',
        isOnline: true,
        friends: [],
        posts: [],
        inFriendRequest: [],
        outFriendRequest: [],
        unreadMessages: [],
    },
    {
        id: '2024-03-19T18:25:18.125Z',
        username: 'Rocky',
        email: 'test@admin.com',
        password: '123',
        isOnline: true,
        friends: [],
        posts: [],
        inFriendRequest: [],
        outFriendRequest: [],
        unreadMessages: [],
    },
    {
        id: '2024-03-19T18:25:34.177Z',
        username: 'Мартин Петров',
        email: 'test22@admin.com',
        password: 'adcs',
        isOnline: true,
        friends: [],
        posts: [],
        inFriendRequest: [],
        outFriendRequest: [],
        unreadMessages: [],
    },
    {
        id: '2024-03-20T09:11:56.622Z',
        username: 'Петя',
        email: 'test1@admin.com',
        password: '123',
        isOnline: true,
        friends: [],
        posts: [],
        inFriendRequest: [],
        outFriendRequest: [],
        unreadMessages: [],
    },
];

export const mockPosts: IPost[] = [
    {
        id: '1710872333965',
        author: {
            id: 'Tue Mar 19 2024 21:18:47 GMT+0300 (Москва, стандартное время)',
            username: 'Ваня',
            email: 'test@admin.com',
            password: '111',
            isOnline: true,
            friends: [],
            posts: [],
            inFriendRequest: [],
            outFriendRequest: [],
            unreadMessages: [],
        },
        content: 'werf',
        createdAt: '2024-03-19T18:18:53.965Z',
        imgUrls: [],
    },
    {
        id: '1710872359073',
        author: {
            id: 'Tue Mar 19 2024 21:18:47 GMT+0300 (Москва, стандартное время)',
            username: 'Ваня',
            email: 'test@admin.com',
            password: '111',
            isOnline: true,
            friends: [],
            posts: [],
            inFriendRequest: [],
            outFriendRequest: [],
            unreadMessages: [],
        },
        content: 'Новый пост\n\n',
        createdAt: '2024-03-19T18:19:19.073Z',
        imgUrls: [],
    },
    {
        id: '1710872408963',
        author: {
            id: 'Tue Mar 19 2024 21:19:54 GMT+0300 (Москва, стандартное время)',
            username: 'Ира Петрова',
            email: 'test@admin.com',
            password: '12345',
            isOnline: true,
            friends: [],
            posts: [],
            inFriendRequest: [],
            outFriendRequest: [],
            unreadMessages: [],
        },
        content: 'Проверка',
        createdAt: '2024-03-19T18:20:08.963Z',
        imgUrls: [],
    },
    {
        id: '1710872417389',
        author: {
            id: 'Tue Mar 19 2024 21:19:54 GMT+0300 (Москва, стандартное время)',
            username: 'Ира Петрова',
            email: 'test@admin.com',
            password: '12345',
            isOnline: true,
            friends: [],
            posts: [],
            inFriendRequest: [],
            outFriendRequest: [],
            unreadMessages: [],
        },
        content: 'Работает',
        createdAt: '2024-03-19T18:20:17.389Z',
        imgUrls: [],
    },
    {
        id: '1710926059398',
        author: {
            id: 'Tue Mar 19 2024 14:41:24 GMT+0300 (Москва, стандартное время)',
            username: 'Петя',
            email: 'test@admin.com',
            password: '123',
            isOnline: true,
            friends: [],
            posts: [],
            inFriendRequest: [],
            outFriendRequest: [],
            unreadMessages: [],
        },
        content: 'Пост ',
        createdAt: '2024-03-20T09:14:19.398Z',
        imgUrls: [],
    },
];

export const mockComments: IComment[] = [
    {
        author: {
            id: '2t',
            password: 'password',
            username: 'Pete',
            email: 'james@gmail.com',
            avatarUrl: 'https://api.dicebear.com/7.x/adventurer-neutral/svg',
            isOnline: true,
            friends: [],
            inFriendRequest: [],
            outFriendRequest: [],
            unreadMessages: [],
        },
        createdAt: '2024-03-19T17:54:56.131Z',
        id: '23',
        content: 'comment test',
        postId: '2323',
    },
    {
        author: {
            id: '2t',
            password: 'password',
            username: 'Pete1',
            email: 'james@gmail.com',
            avatarUrl: 'https://api.dicebear.com/7.x/adventurer-neutral/svg',
            isOnline: true,
            friends: [],
            inFriendRequest: [],
            outFriendRequest: [],
            unreadMessages: [],
        },
        createdAt: '2024-03-19T17:54:56.131Z',
        id: '213',
        content: 'comment test',
        postId: '2323',
    },
    {
        author: {
            id: '2t',
            password: 'password',
            username: 'Pete2',
            email: 'james@gmail.com',
            avatarUrl: 'https://api.dicebear.com/7.x/adventurer-neutral/svg',
            isOnline: true,
            friends: [],
            inFriendRequest: [],
            outFriendRequest: [],
            unreadMessages: [],
        },
        createdAt: '2024-03-19T17:54:56.131Z',
        id: '123',
        content: 'comment test',
        postId: '2323',
    },
    {
        author: {
            id: '2t',
            password: 'password',
            username: 'Pete3',
            email: 'james@gmail.com',
            avatarUrl: 'https://api.dicebear.com/7.x/adventurer-neutral/svg',
            isOnline: true,
            friends: [],
            inFriendRequest: [],
            outFriendRequest: [],
            unreadMessages: [],
        },
        createdAt: '2024-03-19T17:54:56.131Z',
        id: '2113',
        content: 'comment test',
        postId: '2323',
    },
    {
        author: {
            id: '2t',
            password: 'password',
            username: 'Pete4',
            email: 'james@gmail.com',
            avatarUrl: 'https://api.dicebear.com/7.x/adventurer-neutral/svg',
            isOnline: true,
            friends: [],
            inFriendRequest: [],
            outFriendRequest: [],
            unreadMessages: [],
        },
        createdAt: '2024-03-19T17:54:56.131Z',
        id: '1223',
        content: 'comment test wwww',
        postId: '2323',
    },
];

export const mockMessages = [
    {
        senderId: '1',
        receiverId: '2',
        text: 'Message 1 from John to Pete',
        timestamp: 1648121840000,
        id: '2024-03-23T08:04:00.000Z',
    },
    {
        senderId: '1',
        receiverId: '2',
        text: 'Message 2 from John to Pete',
        timestamp: 1648185720000,
        id: '2024-03-24T00:22:00.000Z',
    },
    {
        senderId: '1',
        receiverId: '3',
        text: 'Message 1 from John to Ann',
        timestamp: 1648147320000,
        id: '2024-03-23T15:15:20.000Z',
    },
    {
        senderId: '2',
        receiverId: '3',
        text: 'Message 1 from Pete to Ann',
        timestamp: 1648147380000,
        id: '2024-03-23T15:16:20.000Z',
    },
    {
        senderId: '3',
        receiverId: '4',
        text: 'Message 1 from Ann to Tom',
        timestamp: 1648147440000,
        id: '2024-03-23T15:17:20.000Z',
    },
];
